# Chapter 5. The Basics of Numpy Arrays
**This chapter will present several examples of using NumPy
array manipulation to access data and subarrays, and to split, reshape, and
join the arrays.**

In [1]:
import numpy as np

## Array Attributes

In [5]:
# we'll use numpy random number generator
rng = np.random.default_rng(seed=1702)
# we have used seed to ensure the same random array are generated each timethis code is run

In [7]:
x1 = rng.integers(10,size=6)# one dimensional array
x2 = rng.integers(10,size=(3,4)) # two dimensional array
x3 = rng.integers(10,size=(3,4,5)) # three dimensional array

### Each array has attributes including ndim (the number of dimensions),shape (the size of each dimension), size (the total size of the array), and dtype (the type of each element):

In [8]:
print("x3 ndim: ",x3.ndim)

x3 ndim:  3


In [9]:
print("x3 shape: ",x3.shape)

x3 shape:  (3, 4, 5)


In [10]:
print("x3 size: ",x3.size)

x3 size:  60


In [11]:
print("x3 dtype: ",x3.dtype)

x3 dtype:  int64


In [12]:
x1

array([8, 1, 4, 7, 5, 3])

## Array Slicing: Accessing Subarrays

### One-Dimensional Subarrays

In [13]:
x1[:3] # outputs for the 0 to 2 Index

array([8, 1, 4])

In [15]:
x1[3:] #outputs from 3 to the end 

array([7, 5, 3])

In [16]:
x1[1:4] # outputs from 1 index to 3 index

array([1, 4, 7])

In [19]:
x1[::2] # outputs fromt the first element then the second(2) jumps 1 element

array([8, 4, 5])

In [20]:
x1[::3] #outputs form the first and jumps 2

array([8, 7])

In [21]:
x1[1::2] #outputs from the index[1] then jumps 1 element

array([1, 7, 3])

In [22]:
x1[::-1] # all elements , reversed

array([3, 5, 7, 4, 1, 8])

In [23]:
x1[4::-2] # array([8, 1, 4, 7, 5, 3]) starts from index[4] the reverse jumping 1 elements

array([5, 4, 8])

### Multidimensional Subarrays

In [24]:
x2

array([[9, 1, 1, 1],
       [1, 3, 6, 4],
       [3, 3, 7, 5]])

In [27]:
x2[:2,:3] #starts from 0 rows to 2 row and from 0 column to 2 column

array([[9, 1, 1],
       [1, 3, 6]])

In [28]:
x2[:3,::2] #start for 0 rows to 3 rows then on the column it jumps 1

array([[9, 1],
       [1, 6],
       [3, 7]])

In [30]:
x2[::-1,::-1] #all rows and columns,reversed

array([[5, 7, 3, 3],
       [4, 6, 3, 1],
       [1, 1, 1, 9]])

In [31]:
x2[:,0]

array([9, 1, 3])

**Subarrays as No-Copy Views**

In [32]:
print(x2)

[[9 1 1 1]
 [1 3 6 4]
 [3 3 7 5]]


In [34]:
x2_copy=x2[:2,:2]
print(x2_copy)

[[9 1]
 [1 3]]


In [35]:
x2_copy[0,0] = 99
print(x2_copy)

[[99  1]
 [ 1  3]]


In [37]:
print(x2) # if we modify this subarray, we’ll see that the original array is changed!

[[99  1  1  1]
 [ 1  3  6  4]
 [ 3  3  7  5]]


### Creating Copies of Arrays

In [38]:
x2_copy = x2[:2,:2].copy()
print(x2_copy)

[[99  1]
 [ 1  3]]


In [39]:
x2_copy[0,0]=21

In [42]:
print(x2_copy)
print("-------")
print(x2)

[[21  1]
 [ 1  3]]
-------
[[99  1  1  1]
 [ 1  3  6  4]
 [ 3  3  7  5]]


## Reshaping of Arrays

In [43]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
x = np.arange(1,4)
x.reshape((1,3))

array([[1, 2, 3]])

In [48]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

**alternative**

In [50]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [51]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Array Concatenation and Splitting

In [52]:
x = np.array([1,2,3])

In [53]:
y = np.array([3,2,1])

In [55]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [57]:
z = np.array([99,99,88])
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 88]


In [58]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.concatenate([grid,grid]) # concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.concatenate([grid,grid],axis=1) # concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [62]:
#vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# horizontally stack the arrays
y = np.array([[99],
               [99],[99]])
np.hstack([grid,y])#the number of rows must be the same

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

### Splitting of Arrays

In [69]:
x = np.array([1,2,4,99,00,3,2,1])

In [70]:
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 4] [99  0] [3 2 1]


In [72]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
upper,lower = np.vsplit(grid,[2])
print("upper ",upper)
print("lower ",lower) 

upper  [[0 1 2 3]
 [4 5 6 7]]
lower  [[ 8  9 10 11]
 [12 13 14 15]]


In [75]:
left,right = np.hsplit(grid,[2])
print("left ",left)
print("right ",right)

left  [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right  [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
