# Chapter 6. Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701)

In [6]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [7]:
values = rng.integers(1,10,size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

**This implementation probably feels fairly natural to someone from, say, a C
or Java background. But if we measure the execution time of this code for a
large input, we see that this operation is very slow**

In [11]:
big_array = rng.integers(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

2.55 s ± 117 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
print(compute_reciprocals(values))
print("---------")
print(1.0/values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
---------
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [16]:
%timeit (1.0/ big_array)

4.35 ms ± 185 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
np.arange(5) /np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

### Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which operate on two inputs.

In [23]:
x = np.arange(4)
print("x    =",x)
print("x + 5 =",x+5)
# numpy has ufuncs build in for add
np.add(x,2)

x    = [0 1 2 3]
x + 5 = [5 6 7 8]


array([2, 3, 4, 5])

In [28]:
print("x -5 =",x-5)
print("x * 2=",x*2)
# numpy built in ufunc
print(np.subtract(x,5))

np.multiply(x,2)

x -5 = [-5 -4 -3 -2]
x * 2= [0 2 4 6]
[-5 -4 -3 -2]


array([0, 2, 4, 6])

In [33]:
print("x / 2 = ",x/2)
print("x // 2 = ",x //2)
print(np.divide(x,2))
np.floor_divide(x,2)# This is not modulus but floor division(rounds off to floor)

x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]
[0.  0.5 1.  1.5]


array([0, 0, 1, 1])

In [32]:
print("-x  = ",-x) #negation
print("x **2 = ",x**2) #exponentiation
np.power(x,2)

-x  =  [ 0 -1 -2 -3]
x **2 =  [0 1 4 9]


array([0, 1, 4, 9])

In [34]:
print("x % 2 = ",x%2) #modulus
np.mod(x,2)

x % 2 =  [0 1 0 1]


array([0, 1, 0, 1])

## Trigonometric Functions

In [35]:
theta = np.linspace(0,np.pi,3)

In [37]:
print("theta = ",theta)
print("sin (theta) ",np.sin(theta))
print("cos (theta) ",np.cos(theta))
print("tan (theta) ",np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin (theta)  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos (theta)  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan (theta)  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


## Exponents and Logarithms

In [45]:
x  = [1,2,3]
print("x =",x)
print("e^x = ",np.exp(x))
print("2^x = ",np.exp2(x))
print("3^x = ",np.power(3,x))

x = [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [47]:
x = np.array([1,2,4,10])
print("ln(x) =",np.log(x))
print("log2(x) =",np.log2(x))
print("log10(x) = ",np.log10(x))

ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


**Specifying Output**

In [48]:
x = np.arange(5)
y = np.empty(5)


array([0.0e+000, 4.9e-324, 9.9e-324, 1.5e-323, 2.0e-323])

In [49]:
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


### Aggregations
    Aggregation means combining multiple values into one using some rule.

In programming and data science, it often means:

    Applying a function (like sum, mean, max) to a group of values to get a single result.

In [52]:
x = np.arange(1,6)
np.add.reduce(x)

np.int64(15)

In [53]:
np.multiply.reduce(x)

np.int64(120)

In [54]:
np.add.accumulate(x) # if we would like to store all the intermediate results of computation

array([ 1,  3,  6, 10, 15])