# Chapter 9. Comparisons,Masks, and Boolean Logic
covers the use of Boolean masks to examine and manipulate values within NumPy arrays.

In [1]:
import numpy as np

In [3]:
x = np.arange(6)
y = np.arange(4,10)

In [10]:
print(np.equal(x,y))

print(x)
print(y)
y[4]=4
np.equal(x,y)

[False False False False False False]
[0 1 2 3 4 5]
[4 5 6 7 8 9]


array([False, False, False, False,  True, False])

In [11]:
np.less(x,y)

array([ True,  True,  True,  True, False,  True])

In [13]:
np.any(x>y)

np.False_

In [14]:
#masking
x[x<4]

array([0, 1, 2, 3])

In [16]:
x | y

array([ 4,  5,  6,  7,  4, 13])

In [20]:
(x<3)& (y>5)

array([False, False,  True, False, False, False])