# 📌 1. Regular Indexing

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40])
print(arr[2])

30


# 📌 2. Slicing

In [5]:
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [6]:
print(arr[1:4]) #slicing

[20 30 40]


# 📌 3. Fancy Indexing 🎩
Selecting multiple arbitrary elements using a list (or array) of indices

In [7]:
choosed = [3,2,0,1]
print(f"The choosen are : {arr[choosed]}")

The choosen are : [40 30 10 20]


In [10]:
mat = np.array([[1, 2], [3, 4], [5, 6]])
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:

print(mat[[0, 2]])  # Rows 0 and 2

[[1 2]
 [5 6]]


In [16]:
mat[[0,1],[1]]

array([2, 4])

# 📌 4. Boolean Masking (aka Boolean Indexing) 🎭

In [18]:
mask = arr > 25
print(mask)         # [False False  True  True  True]
print(arr[mask])

[False False  True  True  True]
[30 40 50]


In [20]:
# alternative
print(arr[arr>25])

[30 40 50]


In [21]:
print(arr[arr<35])

[10 20 30]
