# This is Week 2 learning about jupyter,numpy and pandas

In [11]:
print("Hello Jupyter")

Hello Jupyter


## Numpy 

In [3]:
import numpy as np

In [6]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [7]:
type(x)

numpy.ndarray

In [14]:
a = np.array([1,3,4,6,0])

In [15]:
b = np.array((2,4,6))

In [16]:
print(a)

[1 3 4 6 0]


In [17]:
type(a)

numpy.ndarray

In [18]:
a.dtype


dtype('int64')

In [19]:
print(b)


[2 4 6]


In [20]:
type(b)


numpy.ndarray

In [21]:
b.dtype

dtype('int64')

### one can explicity specify the data type of an array this way

In [22]:
b = np.array((3,4,5),dtype='f')


In [23]:
b.dtype

dtype('float32')

In [24]:
print(b)


[3. 4. 5.]


## Creating Arrays from Scratch

In [28]:
# create a length 10 integer array filled with 0s
np.zeros(10,dtype='i')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [29]:
# create a 3*5 floating poin array filled with 1s
np.ones((3,5),dtype='f')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [30]:
# create a 3*5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [31]:
# create an array filled with a linear sequence 
# starting at 0, ending at 20, stepping by 2(similar to built-in range function
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
#create an array of 5 values evenly spaced between 0 and 6
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
# create a 3*3 array of uniformly distributed
# pseudorandom values between 0 and 1
np.random.random((3,3))

array([[0.43297272, 0.16106552, 0.31764973],
       [0.24902014, 0.45312119, 0.37415708],
       [0.5735446 , 0.84191905, 0.34147024]])

In [7]:
#create a 3*3 array of normally distributed pseaudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-1.3799456 , -3.08021539, -0.22878844],
       [ 1.64085835, -0.64965052, -1.24983733],
       [-0.26346792, -1.49155287, -0.48176463]])

In [9]:
# create a 3*3 array of pseaudorandom integers in the interval (0,10)
np.random.randint(0,10,(3,3))

array([[1, 0, 2],
       [0, 7, 9],
       [1, 9, 0]])

In [10]:
# create a 3*3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
# create an uninitialized array of three integers the vlues will be
# whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])